#*************************************************************
#
#	A very simple Makefile for Copymask and other tools
#
#	TODO
#
#*************************************************************




default:
	@$(CC) CopyRom.c -o CopyRom
	@printf "done\n"

clean:
	rm CopyRom
