#*************************************************************
#
#	A very simple Makefile for Copymask and other tools
#
#	TODO
#
#*************************************************************

CC = gcc


default:
	@gcc CopyRom.c -o CopyRom
	@printf "done\n"

clean:
	rm copymask
